[Global]
# Always start Mozc in hiragana (not direct/latin input)
InitialMode=Hiragana
# Share the input mode between apps
InputState="Follow Global Configuration"
Vertical=True
ExpandMode="On Focus"
